### PR TITLE
add a stub file to comply with PEP 561

### PR DESCRIPTION
**Pull request by desaleo**
Proposal (again): Add a py.typed file to ensure compliance with PEP 561. This will prevent users with strict type checkers (like me), from encountering error messages.

### CODE REVIEW

**Comment by mark9064** [comment]
Good catch, I didn't know libraries need to specify this explicitly! Doing some research, it looks like modern setuptools (>=61, we require >=62) with pyproject.toml includes data files by default, so this should work without build config changes. I'm not 100% sure how to test this though: what's the easiest way to check if type checking is working for the library (which strict options do I need to use)? Or if you've already tested locally I'll take your word for it :)

**Comment by desaleo** [comment]
> Good catch, I didn't know libraries need to specify this explicitly! 

I didn't know either I just randomly decided to pass my python type checker (pyright, integrated with VSCode) in strict mode to improve code quality and it triggered this rule: https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingTypeStubs
> Doing some research, it looks like modern setuptools (>=61, we require >=62) with pyproject.toml includes data files by default, so this should work without build config changes. 

It look like I got a little too fast and the right way to add a py.typed file to the project is to add this line to the toml instead of directly including the file in the project:
```toml
[tool.setuptools.package-data]
"*" = ["py.typed"]
```
source: https://jugmac00.github.io/blog/bite-my-shiny-type-annotated-library/#setuptools-and-pyprojecttoml

> I'm not 100% sure how to test this though: what's the easiest way to check if type checking is working for the library (which strict options do I need to use)?

To test the modification of the pyproject.toml I just used ``python -m pip install .``
and to turn vscode to strict mode I added this line in my .vscode/settings.json after opening my project with vscode
```json
"python.analysis.typeCheckingMode": "strict"
```
instead of the default
```json
"python.analysis.typeCheckingMode": "basic"
```

> Or if you've already tested locally I'll take your word for it :)

I appreciate the trust you have in me but in the domain of package distribution i'm just a enlightened amateur 😂

**Comment by mark9064** [comment]
I'm pretty sure you had it right beforehand. You still need a `py.typed` file either way - that blog post you linked just adds the code to ensure it's included in the distributed release. I made a test wheel after only adding the file and it was in there, so provided that actually works we don't need to change the pyproject file (this is what I was talking about when I said versions >=62 includes other files by default - I still might be wrong on this but that was what I was getting at). I don't use pylance because I'm not interested in a closed source language server so I can't reproduce your config but I'll try with mypy/pyright.

**Comment by mark9064** [comment]
Yep, looks like the original commit was perfect. I created a small test file with some type errors, and then ran mypy before and then afterwards with py.typed added
```
/tmp/testcode  mypy a.py
a.py:1: error: Skipping analyzing "factorio_rcon": module is installed, but missing library stubs or py.typed marker  [import-untyped]
a.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
 /tmp/testcode  mypy a.py
a.py:3: error: Argument 1 to "RCONClient" has incompatible type "int"; expected "str"  [arg-type]
a.py:3: error: Argument 3 to "RCONClient" has incompatible type "list[str]"; expected "str"  [arg-type]
Found 3 errors in 1 file (checked 1 source file)
 /tmp/testcode 
 ```

**Comment by desaleo** [comment]
let's do that then 👍

**Comment by desaleo** [comment]
it looks like there is still one problem, pyright and mypy in strict mode consider that "imported symbols are considered private by default, except if they use the ``import A as A`` (a redundant module alias)." ([to quote the documentation](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface)) this seems to be a common practice and i've found several libraries doing it (like aiohttp or pytorch), so if I can be annoying one last time may I propose one last commit?

**Comment by mark9064** [comment]
Hmm, I think I might know what the issue is (need to restructure package). But I need to do some further reading on modern practice regarding packaging python software which I don't have the time for right now. Unfortunately it's looking like I won't get a chance for a good while (maybe as far as some time in June) but I will look into this when I can. Feel free to poke me occasionally on this!

**Comment by desaleo** [comment]
i don't know why but i already pushed a commit to fix this issue but it doesn't appear here

**Comment by mark9064** [comment]
Yeah, since this change is already merged you would have to open a new PR

**Pull request merged**
